import { useMemo, useState } from "react";
import { useStore } from "../data/useStore.js";
import { commit, getState, undo } from "../data/store.js";
import { useVoice } from "../voice/VoiceProvider.jsx";
import {
  PageHead, Card, Button, IconButton, Sheet, EmptyState, SectionHeader,
  Segmented, useConfirm, useToast, Cell, CellGroup,
} from "../ui/kit.jsx";
import {
  IcSparkle, IcNote, IcTrash, IcCheck, IcRefresh, IcSun, IcMoon, IcSpeaker,
} from "../ui/icons.jsx";
import { dayKey, dayLabel, minsOfDay, ago } from "../lib/time.js";

// ─── Brief ───────────────────────────────────────────────────────────────────
// Two documents a day and everything SYNC has written for you to send. The
// briefs are generated by the same agent loop as everything else, which means
// they're written from the live plan and queue rather than from a template.

function BriefCard({ brief, kind, onWrite, busy }) {
  const voice = useVoice();
  if (!brief) {
    const morning = kind === "morning";
    return (
      <Card pad="lg">
        <EmptyState
          icon={morning ? <IcSun size={26} /> : <IcMoon size={26} />}
          title={morning ? "No brief yet today" : "No debrief yet"}
          sub={morning
            ? "One read of the whole day — what matters, in what order, and what to open first."
            : "What actually got done, what slipped, and the single thing tomorrow should start with."}
          action={<Button kind="primary" size="md" onClick={onWrite} disabled={busy}><IcSparkle size={15} /> {morning ? "Write the brief" : "Debrief the day"}</Button>}
        />
      </Card>
    );
  }
  return (
    <Card pad="lg" style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }}>
        <div style={{ minWidth: 0 }}>
          <div className="t-label">{kind === "morning" ? "Morning brief" : "Debrief"} · {dayLabel(brief.day)}</div>
          {brief.headline && <div className="t-title2" style={{ marginTop: 6 }}>{brief.headline}</div>}
        </div>
        <span style={{ display: "flex", gap: 2, flex: "none" }}>
          <IconButton label="Read it aloud" onClick={() => voice.speak(brief.body)}><IcSpeaker size={17} /></IconButton>
          <IconButton label="Rewrite" onClick={onWrite} disabled={busy}><IcRefresh size={17} /></IconButton>
        </span>
      </div>
      <div className="t-body" style={{ whiteSpace: "pre-wrap", color: "var(--ink)" }}>{brief.body}</div>
      <div className="t-cap" style={{ color: "var(--faint)" }}>Filed {ago(brief.createdAt)}</div>
    </Card>
  );
}

function DraftSheet({ draft, onClose }) {
  const toast = useToast();
  const [confirmEl, confirm] = useConfirm();
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(draft.body);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      toast("Couldn't reach the clipboard — select the text and copy it.", { err: true });
    }
  };

  const remove = async () => {
    if (!(await confirm({ title: `Delete "${draft.title}"?`, confirmLabel: "Delete", destructive: true }))) return;
    commit({
      action: "delete_draft", title: `Deleted draft "${draft.title}"`, touches: ["drafts"],
      apply: (s) => ({ drafts: s.drafts.filter((d) => d.id !== draft.id) }),
    });
    toast("Deleted", { action: () => undo(getState().ledger[getState().ledger.length - 1].id), actionLabel: "Undo" });
    onClose();
  };

  return (
    <>
      {confirmEl}
      <Sheet
        onClose={onClose}
        title={draft.title}
        footer={
          <>
            <Button kind="danger" size="lg" onClick={remove}><IcTrash size={16} /></Button>
            <Button kind="quiet" size="lg" style={{ flex: 1 }} onClick={onClose}>Close</Button>
            <Button kind="primary" size="lg" style={{ flex: 1 }} onClick={copy}>
              {copied ? <><IcCheck size={16} /> Copied</> : "Copy"}
            </Button>
          </>
        }
      >
        <div className="t-cap" style={{ color: "var(--faint)", marginBottom: 10 }}>
          {draft.kind} · {draft.body.trim().split(/\s+/).length} words · {ago(draft.createdAt)}
        </div>
        <div
          className="t-body"
          style={{ whiteSpace: "pre-wrap", background: "var(--surface-2)", padding: 14, borderRadius: 12, userSelect: "text" }}
        >
          {draft.body}
        </div>
      </Sheet>
    </>
  );
}

export default function BriefPage() {
  const s = useStore();
  const voice = useVoice();
  const [tab, setTab] = useState(minsOfDay() < 15 * 60 ? "morning" : "evening");
  const [open, setOpen] = useState(null);
  const today = dayKey();

  const morning = useMemo(() => s.briefs.find((b) => b.day === today && b.kind === "morning"), [s.briefs, today]);
  const evening = useMemo(() => s.briefs.find((b) => b.day === today && b.kind === "evening"), [s.briefs, today]);
  const drafts = useMemo(() => [...s.drafts].reverse(), [s.drafts]);
  const earlier = useMemo(() => s.briefs.filter((b) => b.day !== today).slice().reverse(), [s.briefs, today]);

  const writeMorning = () => voice.send(
    "Write my morning brief. Read the plan and the queue first. Lead with the single thing that matters most today, then what's actually scheduled, then anything overdue or waiting on someone else. Say it the way you'd say it out loud, then file it with write_brief."
  );

  const writeEvening = () => voice.send(
    "Debrief today. What got closed, what slipped and why, what's still waiting on someone else, and the one thing tomorrow should open with. Be honest about what didn't happen. File it with write_brief as the evening brief."
  );

  return (
    <>
      <PageHead
        title="Brief"
        sub={`${dayLabel(today, { long: true })} · ${drafts.length} draft${drafts.length === 1 ? "" : "s"} on hand`}
      />

      <div className="content-scroll">
        <div className="content-max">
          <Segmented
            options={[
              { key: "morning", label: "Morning" },
              { key: "evening", label: "Debrief" },
              { key: "drafts", label: "Drafts", sub: drafts.length ? String(drafts.length) : undefined },
            ]}
            value={tab}
            onChange={setTab}
            style={{ marginBottom: 14 }}
          />

          <div className="pagefade" key={tab}>
            {tab === "morning" && (
              <BriefCard brief={morning} kind="morning" onWrite={writeMorning} busy={voice.busy} />
            )}

            {tab === "evening" && (
              <BriefCard brief={evening} kind="evening" onWrite={writeEvening} busy={voice.busy} />
            )}

            {tab === "drafts" && (
              drafts.length === 0 ? (
                <Card pad="lg">
                  <EmptyState
                    icon={<IcNote size={26} />}
                    title="Nothing drafted yet"
                    sub="Ask SYNC to write something — an outreach email, ad copy, a reply you're dreading — and it lands here ready to copy."
                    action={
                      <Button kind="primary" size="md" onClick={() => voice.send("Draft the highest-leverage outreach message I could send today. Pick the target yourself from what you know about my ventures, and tell me why that one.")}>
                        <IcSparkle size={15} /> Have SYNC draft something
                      </Button>
                    }
                  />
                </Card>
              ) : (
                <CellGroup className="stagger">
                  {drafts.map((d) => (
                    <Cell
                      key={d.id}
                      leading={<IcNote size={15} />}
                      leadingTone="var(--accent)"
                      title={d.title}
                      sub={`${d.kind} · ${d.body.trim().split(/\s+/).length} words · ${ago(d.createdAt)}`}
                      chevron
                      onClick={() => setOpen(d)}
                    />
                  ))}
                </CellGroup>
              )
            )}

            {tab !== "drafts" && earlier.length > 0 && (
              <>
                <SectionHeader title="Earlier" style={{ marginTop: 24 }} />
                <CellGroup>
                  {earlier.filter((b) => b.kind === tab).slice(0, 14).map((b) => (
                    <Cell
                      key={b.id}
                      leading={b.kind === "morning" ? <IcSun size={15} /> : <IcMoon size={15} />}
                      leadingTone="var(--faint)"
                      title={dayLabel(b.day)}
                      sub={b.headline || b.body.slice(0, 80)}
                      chevron
                      onClick={() => setOpen({ ...b, title: `${dayLabel(b.day)} — ${b.kind} brief`, kind: "brief" })}
                    />
                  ))}
                </CellGroup>
              </>
            )}
          </div>
        </div>
      </div>

      {open && <DraftSheet draft={open} onClose={() => setOpen(null)} />}
    </>
  );
}
