-- Pentagon audit hardening: the project is a single-operator workspace, so a
-- generic authenticated user must not inherit its CRM, outreach, or operations
-- data. public.is_operator() is an existing security-definer allow-list check.

begin;

do $$
declare
  target_table text;
  target_policy text;
begin
  foreach target_table in array array[
    'app_settings', 'contacts', 'messages', 'outreach', 'prospecting_runs',
    'prospects', 'sequence_enrollments', 'sequence_steps', 'sequences',
    'tone_memory', 'tracked_links'
  ] loop
    for target_policy in
      select p.policyname from pg_policies p
      where p.schemaname = 'public' and p.tablename = target_table
    loop
      execute format('drop policy if exists %I on public.%I', target_policy, target_table);
    end loop;

    execute format('revoke all on table public.%I from anon, authenticated', target_table);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', target_table);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_operator()) with check (public.is_operator())',
      target_table || '_operator_only', target_table
    );
  end loop;
end $$;

-- These two tables are generated by scheduled/service work. The browser only
-- needs to read them, and only the operator should see even that output.
do $$
declare
  target_table text;
  target_policy text;
begin
  foreach target_table in array array['ops_runs', 'zts_store_daily'] loop
    for target_policy in
      select p.policyname from pg_policies p
      where p.schemaname = 'public' and p.tablename = target_table
    loop
      execute format('drop policy if exists %I on public.%I', target_policy, target_table);
    end loop;

    execute format('revoke all on table public.%I from anon, authenticated', target_table);
    execute format('grant select on table public.%I to authenticated', target_table);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.is_operator())',
      target_table || '_operator_read', target_table
    );
  end loop;
end $$;

-- Public lead capture remains intentionally insert-only. The operator can read
-- and manage it; anonymous callers cannot enumerate, modify, or delete leads.
do $$
declare target_policy text;
begin
  for target_policy in
    select p.policyname from pg_policies p
    where p.schemaname = 'public' and p.tablename = 'audit_requests'
  loop
    execute format('drop policy if exists %I on public.audit_requests', target_policy);
  end loop;
end $$;

revoke all on table public.audit_requests from anon, authenticated;
grant insert on table public.audit_requests to anon;
grant select, insert, update, delete on table public.audit_requests to authenticated;
create policy audit_requests_public_insert on public.audit_requests
  for insert to anon with check (true);
create policy audit_requests_operator_only on public.audit_requests
  for all to authenticated using (public.is_operator()) with check (public.is_operator());

-- Open/click events must be recordable by a mail client without a login, but
-- they are telemetry, not public data. Keep exactly that one write capability.
do $$
declare target_policy text;
begin
  for target_policy in
    select p.policyname from pg_policies p
    where p.schemaname = 'public' and p.tablename = 'email_events'
  loop
    execute format('drop policy if exists %I on public.email_events', target_policy);
  end loop;
end $$;

revoke all on table public.email_events from anon, authenticated;
grant insert on table public.email_events to anon;
grant select on table public.email_events to authenticated;
create policy email_events_public_insert on public.email_events
  for insert to anon with check (true);
create policy email_events_operator_read on public.email_events
  for select to authenticated using (public.is_operator());

-- Replace direct anonymous rate_events access with one atomic claim. The caller
-- supplies an HMACed IP hash, so a direct caller cannot target a real visitor's
-- bucket without the function-only AUDIT_RATE_LIMIT_SALT.
do $$
declare target_policy text;
begin
  for target_policy in
    select p.policyname from pg_policies p
    where p.schemaname = 'public' and p.tablename = 'rate_events'
  loop
    execute format('drop policy if exists %I on public.rate_events', target_policy);
  end loop;
end $$;

revoke all on table public.rate_events from anon, authenticated;

create or replace function public.claim_audit_rate(p_ip_hash text, p_limit integer default 4)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  effective_limit integer := greatest(1, least(coalesce(p_limit, 4), 4));
begin
  if p_ip_hash !~ '^[0-9a-f]{32}$' then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtext('audit-rate:' || p_ip_hash));
  delete from public.rate_events
    where ip_hash = p_ip_hash
      and created_at < now() - interval '1 hour';

  if exists (
    select 1 from public.rate_events
    where ip_hash = p_ip_hash
      and kind = 'audit'
      and created_at >= now() - interval '1 hour'
    group by ip_hash
    having count(*) >= effective_limit
  ) then
    return false;
  end if;

  insert into public.rate_events (ip_hash, kind) values (p_ip_hash, 'audit');
  return true;
end;
$$;

revoke all on function public.claim_audit_rate(text, integer) from public;
grant execute on function public.claim_audit_rate(text, integer) to anon, authenticated;

-- A tracked-link UUID is unguessable, but anonymous table SELECT still exposes
-- the table contract. Resolve only the requested row through this RPC instead.
create or replace function public.resolve_tracking_link(p_link_id uuid)
returns table (id uuid, message_id uuid, url text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select l.id, l.message_id, l.url
  from public.tracked_links l
  where l.id = p_link_id
  limit 1;
$$;

revoke all on function public.resolve_tracking_link(uuid) from public;
grant execute on function public.resolve_tracking_link(uuid) to anon, authenticated;

commit;
