// GENERATED by scripts/gen-themes.mjs — do not edit by hand.
  // The picker's list, and the status-bar colour per palette. Full palettes live in
  // design/themes.css; only what the UI needs to render a swatch is duplicated
  // here, and theme-smoke asserts the two never drift.

  export const PALETTES = [
    { key: "zts", label: "ZTS", blurb: "Emerald — Zero To Secure",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#1F7A51", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#4BD296", ink: "#D1D4DB" } },
  { key: "clarify", label: "Clarify", blurb: "Brass — outreach and pipeline",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#83672A", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#C8A456", ink: "#D1D4DB" } },
  { key: "runway", label: "Runway", blurb: "Violet — the job search",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#2D1CAB", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#9489EC", ink: "#D1D4DB" } },
  { key: "macro", label: "Macro", blurb: "Amber — the trading account",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#906109", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#F2AC2C", ink: "#D1D4DB" } },
  { key: "looper", label: "Looper", blurb: "Cyan — browser mission loops",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#147685", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#3CCCE2", ink: "#D1D4DB" } },
  { key: "business", label: "Business", blurb: "Magenta — the autonomous agent",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#AF1863", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#EA66A8", ink: "#D1D4DB" } },
  { key: "sync", label: "SYNC", blurb: "Orchid — the workday layer",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#7316B1", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#BE77EE", ink: "#D1D4DB" } },
  { key: "ideas", label: "Ideas", blurb: "Lime — what showed up on GitHub",
      day: { bg: "#EFF1F5", surface: "#FEFEFE", accent: "#527415", ink: "#22242B" },
      night: { bg: "#0B0E14", surface: "#191D27", accent: "#A3DC41", ink: "#D1D4DB" } },
  ];

  export const DEFAULT_PALETTE = "porcelain";
  export const paletteByKey = (key) => PALETTES.find(p => p.key === key) || PALETTES[0];
  