// GENERATED by packages/design/gen-themes.mjs — do not edit by hand.
  // The picker's list, and the status-bar colour per palette. Full palettes live in
  // design/themes.css; only what the UI needs to render a swatch is duplicated
  // here, and theme-smoke asserts the two never drift.

  export const PALETTES = [
    { key: "session", label: "Session", blurb: "Board Room — calm blue slate",
      day: { bg: "#F3F5F6", surface: "#FEFEFE", accent: "#2764A5", ink: "#24282E" },
      night: { bg: "#1F2329", surface: "#2D343C", accent: "#87B4E3", ink: "#E8EAED" } },
  { key: "zts", label: "ZTS", blurb: "Emerald — Zero To Secure",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#247A53", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#72D5A8", ink: "#E9EAED" } },
  { key: "clarify", label: "Clarify", blurb: "Blue steel — outreach and pipeline",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#2E6999", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#89B7DC", ink: "#E9EAED" } },
  { key: "runway", label: "Runway", blurb: "Violet — the job search",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#372A9D", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#B2AAE9", ink: "#E9EAED" } },
  { key: "macro", label: "Macro", blurb: "Amber — the trading account",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#886420", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#DCB46A", ink: "#E9EAED" } },
  { key: "looper", label: "Looper", blurb: "Cyan — browser mission loops",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#227481", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#6ECAD8", ink: "#E9EAED" } },
  { key: "business", label: "Business", blurb: "Magenta — the autonomous agent",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#9D2A63", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#E49ABF", ink: "#E9EAED" } },
  { key: "sync", label: "SYNC", blurb: "Orchid — the workday layer",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#6F2A9D", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#CBA2E6", ink: "#E9EAED" } },
  { key: "ideas", label: "Ideas", blurb: "Lime — what showed up on GitHub",
      day: { bg: "#F1F2F4", surface: "#FEFEFE", accent: "#587623", ink: "#22262A" },
      night: { bg: "#202327", surface: "#2F333A", accent: "#B0D572", ink: "#E9EAED" } },
  ];

  export const DEFAULT_PALETTE = "session";
  export const paletteByKey = (key) => PALETTES.find(p => p.key === key) || PALETTES[0];
  