// GENERATED by packages/design/gen-themes.mjs — do not edit by hand.
  // The picker's list, and the status-bar colour per palette. Full palettes live in
  // design/themes.css; only what the UI needs to render a swatch is duplicated
  // here, and theme-smoke asserts the two never drift.

  export const PALETTES = [
    { key: "session", label: "Session", blurb: "Board Room — unified brass",
      day: { bg: "#F2F1EB", surface: "#FFFFFF", accent: "#87681B", ink: "#1D1C18" },
      night: { bg: "#000000", surface: "#1C1C1E", accent: "#D9B45C", ink: "#F3F2EE" } },
  { key: "zts", label: "ZTS", blurb: "Emerald — Zero To Secure",
      day: { bg: "#F0F4F3", surface: "#FEFEFE", accent: "#1F7A51", ink: "#222B27" },
      night: { bg: "#0D1210", surface: "#1B2521", accent: "#4BD296", ink: "#D1DBD8" } },
  { key: "clarify", label: "Clarify", blurb: "Brass — outreach and pipeline",
      day: { bg: "#F4F3F0", surface: "#FEFEFE", accent: "#83672A", ink: "#2B2722" },
      night: { bg: "#12100D", surface: "#25211B", accent: "#C8A456", ink: "#DBD8D1" } },
  { key: "runway", label: "Runway", blurb: "Violet — the job search",
      day: { bg: "#F1F0F4", surface: "#FEFEFE", accent: "#2D1CAB", ink: "#23222B" },
      night: { bg: "#0E0D12", surface: "#1C1B25", accent: "#9489EC", ink: "#D3D1DB" } },
  { key: "macro", label: "Macro", blurb: "Amber — the trading account",
      day: { bg: "#F4F3F0", surface: "#FEFEFE", accent: "#956409", ink: "#2B2722" },
      night: { bg: "#12100D", surface: "#25211B", accent: "#F2AC2C", ink: "#DBD7D1" } },
  { key: "looper", label: "Looper", blurb: "Cyan — browser mission loops",
      day: { bg: "#F0F3F4", surface: "#FEFEFE", accent: "#147685", ink: "#22292B" },
      night: { bg: "#0D1112", surface: "#1B2325", accent: "#3CCCE2", ink: "#D1D9DB" } },
  { key: "business", label: "Business", blurb: "Magenta — the autonomous agent",
      day: { bg: "#F4F0F3", surface: "#FEFEFE", accent: "#AF1863", ink: "#2B2227" },
      night: { bg: "#120D10", surface: "#251B21", accent: "#EA66A8", ink: "#DBD1D7" } },
  { key: "sync", label: "SYNC", blurb: "Orchid — the workday layer",
      day: { bg: "#F3F0F4", surface: "#FEFEFE", accent: "#7316B1", ink: "#27222B" },
      night: { bg: "#100D12", surface: "#211B25", accent: "#BE77EE", ink: "#D7D1DB" } },
  { key: "ideas", label: "Ideas", blurb: "Lime — what showed up on GitHub",
      day: { bg: "#F2F4F0", surface: "#FEFEFE", accent: "#527415", ink: "#272B22" },
      night: { bg: "#0F120D", surface: "#20251B", accent: "#A3DC41", ink: "#D7DBD1" } },
  ];

  export const DEFAULT_PALETTE = "session";
  export const paletteByKey = (key) => PALETTES.find(p => p.key === key) || PALETTES[0];
  